package com.github.ysbbbbbb.kaleidoscopetavern.paper.game;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Pure formatting and icon mapping for the vanilla-client custom-effect HUD. */
final class CustomEffectHudSemantics {
    static final String FONT_KEY = "kaleidoscope_tavern:custom_effects";
    static final String HUD_FONT_KEY = "kaleidoscope_tavern:custom_effects_hud";
    private static final String SEPARATOR = "<dark_gray>  |  </dark_gray>";

    // Mirrors the space provider and glyph pages generated by
    // tools/migrate_legacy.py: chr(0xE300+i)/chr(0xE310+i) advance by
    // +/-HUD_OFFSET_POWERS[i] pixels, frames sit at 0xE320/0xE321 and the
    // per-effect icons at 0xE330/0xE340 plus the shared 0xE100 icon index.
    private static final int[] HUD_OFFSET_POWERS = {256, 128, 64, 32, 16, 8, 4, 2, 1};
    private static final char HUD_BG_ROW1 = '';
    private static final char HUD_BG_ROW2 = '';
    private static final int HUD_ICON_ROW1 = 0xE330;
    private static final int HUD_ICON_ROW2 = 0xE340;
    private static final int HUD_BG_ADVANCE = 25;
    private static final int HUD_ICON_ADVANCE = 19;
    private static final int HUD_SLOT_STEP = 25;
    private static final int HUD_ICON_INSET = 3;

    // The archived Forge registrations mark exactly these two effects as
    // MobEffectCategory.NEUTRAL; the vanilla overlay renders everything that
    // is not beneficial on the second row.
    private static final Set<String> HUD_ROW2_EFFECTS = Set.of(
            "kaleidoscope_tavern:slightly_tipsy",
            "kaleidoscope_tavern:upside_down");

    // The exact particle colours registered in the archived ModEffects: a
    // vanilla client only swirls for real registry effects, so the server
    // replays ENTITY_EFFECT particles with the original colours instead.
    private static final Map<String, Integer> COLORS = Map.ofEntries(
            Map.entry("kaleidoscope_tavern:slightly_tipsy", 0xFFD94A),
            Map.entry("kaleidoscope_tavern:high_heels", 0xE85BAA),
            Map.entry("kaleidoscope_tavern:grass_stealth", 0x71BDE7),
            Map.entry("kaleidoscope_tavern:vision", 0x408997),
            Map.entry("kaleidoscope_tavern:bloody_mary", 0xF73A36),
            Map.entry("kaleidoscope_tavern:ardent_heat", 0xFF6B35),
            Map.entry("kaleidoscope_tavern:long_reach", 0x8B6914),
            Map.entry("kaleidoscope_tavern:tomb_raider", 0xDAA520),
            Map.entry("kaleidoscope_tavern:xp_drain", 0x7CFC00),
            Map.entry("kaleidoscope_tavern:upside_down", 0x9B59B6),
            Map.entry("kaleidoscope_tavern:zenith", 0x87CEEB),
            Map.entry("kaleidoscope_tavern:shriek_attack", 0x0D4C4A));

    static Integer color(String effectId) {
        return COLORS.get(effectId);
    }

    private static final Map<String, String> ICONS = Map.ofEntries(
            Map.entry("kaleidoscope_tavern:slightly_tipsy", "\uE100"),
            Map.entry("kaleidoscope_tavern:high_heels", "\uE101"),
            Map.entry("kaleidoscope_tavern:grass_stealth", "\uE102"),
            Map.entry("kaleidoscope_tavern:vision", "\uE103"),
            Map.entry("kaleidoscope_tavern:bloody_mary", "\uE104"),
            Map.entry("kaleidoscope_tavern:ardent_heat", "\uE105"),
            Map.entry("kaleidoscope_tavern:long_reach", "\uE106"),
            Map.entry("kaleidoscope_tavern:tomb_raider", "\uE107"),
            Map.entry("kaleidoscope_tavern:xp_drain", "\uE108")
    );

    private CustomEffectHudSemantics() {
    }

    static Display describe(String effectId, int remainingTicks, int amplifier) {
        return new Display(
                effectKey(effectId),
                ICONS.get(effectId),
                amplifier > 0 ? "potion.potency." + amplifier : null,
                formatDuration(remainingTicks));
    }

    static String effectKey(String effectId) {
        int separator = effectId.indexOf(':');
        String namespace = separator < 0 ? "minecraft" : effectId.substring(0, separator);
        String path = separator < 0 ? effectId : effectId.substring(separator + 1);
        return "effect." + namespace + "." + path;
    }

    /**
     * Builds the MiniMessage HUD line shared by the built-in boss bar and the
     * {@code %kaleidoscopetavern_effect_hud%} placeholder, so external
     * renderers such as CustomNameplates show exactly the same content.
     */
    static String miniMessageLine(List<EffectEntry> entries) {
        StringBuilder line = new StringBuilder("<!i>");
        boolean first = true;
        for (EffectEntry entry : entries) {
            if (!first) {
                line.append(SEPARATOR);
            }
            line.append(miniMessageEntry(entry));
            first = false;
        }
        return first ? "" : line.toString();
    }

    private static String miniMessageEntry(EffectEntry entry) {
        Display display = describe(entry.effectId(), entry.remainingTicks(), entry.amplifier());
        // Vanilla nests the amplifier inside the duration format, so the inner
        // argument keeps single quotes while the outer argument uses double
        // quotes to stay parseable.
        String name = "<lang:" + display.effectKey() + ">";
        if (display.potencyKey() != null) {
            name = "<lang:potion.withAmplifier:'" + name
                    + "':'<lang:" + display.potencyKey() + ">'>";
        }
        name = "<lang:potion.withDuration:\"" + name + "\":\"" + display.duration() + "\">";
        // Tint each entry with the colour the original mod registered for the
        // effect, expressed as a MiniMessage hex tag; the swirl particles use
        // the same table.
        Integer rgb = COLORS.get(entry.effectId());
        String color = rgb == null ? "blue" : String.format(Locale.ROOT, "#%06X", rgb);
        StringBuilder text = new StringBuilder();
        if (display.icon() != null) {
            text.append("<white><font:").append(FONT_KEY).append('>')
                    .append(display.icon()).append("</font></white> ");
        }
        return text.append('<').append(color).append('>')
                .append(name)
                .append("</").append(color).append('>')
                .toString();
    }

    /**
     * Builds the vanilla-position corner HUD as a zero-advance MiniMessage
     * string.  Boss bar text is centre-anchored, so ending the line with a
     * compensating negative offset keeps its total advance at zero; every
     * absolute position is then measured from the screen centre, matching the
     * vanilla overlay for clients at the configured GUI half-width.
     */
    static String cornerLine(List<EffectEntry> entries, int guiHalfWidth) {
        if (entries.isEmpty()) {
            return "";
        }
        List<EffectEntry> row1 = new ArrayList<>();
        List<EffectEntry> row2 = new ArrayList<>();
        for (EffectEntry entry : entries) {
            (HUD_ROW2_EFFECTS.contains(entry.effectId()) ? row2 : row1).add(entry);
        }
        StringBuilder glyphs = new StringBuilder();
        int advance = 0;
        advance = appendHudRow(glyphs, row1, HUD_BG_ROW1, HUD_ICON_ROW1, guiHalfWidth, advance);
        advance = appendHudRow(glyphs, row2, HUD_BG_ROW2, HUD_ICON_ROW2, guiHalfWidth, advance);
        appendHudOffset(glyphs, -advance);
        return "<!i><shadow:#00000000><white><font:" + HUD_FONT_KEY + ">"
                + glyphs + "</font></white></shadow>";
    }

    private static int appendHudRow(StringBuilder glyphs, List<EffectEntry> row,
                                    char bgChar, int iconBase, int guiHalfWidth, int advance) {
        for (int slot = 0; slot < row.size(); slot++) {
            int bgX = guiHalfWidth - HUD_SLOT_STEP * (slot + 1);
            appendHudOffset(glyphs, bgX - advance);
            glyphs.append(bgChar);
            advance = bgX + HUD_BG_ADVANCE;
            String icon = ICONS.get(row.get(slot).effectId());
            if (icon != null) {
                int iconX = bgX + HUD_ICON_INSET;
                appendHudOffset(glyphs, iconX - advance);
                glyphs.append((char) (iconBase + icon.charAt(0) - 0xE100));
                advance = iconX + HUD_ICON_ADVANCE;
            }
        }
        return advance;
    }

    private static void appendHudOffset(StringBuilder glyphs, int offset) {
        int remaining = Math.abs(offset);
        int base = offset < 0 ? 0xE310 : 0xE300;
        for (int index = 0; index < HUD_OFFSET_POWERS.length; index++) {
            int power = HUD_OFFSET_POWERS[index];
            while (remaining >= power) {
                glyphs.append((char) (base + HUD_OFFSET_POWERS.length - 1 - index));
                remaining -= power;
            }
        }
    }

    static String formatDuration(int ticks) {
        long totalSeconds = Math.max(1L, ticks / 20L);
        long hours = totalSeconds / 3_600L;
        long minutes = totalSeconds % 3_600L / 60L;
        long seconds = totalSeconds % 60L;
        return hours > 0
                ? String.format(Locale.ROOT, "%d:%02d:%02d", hours, minutes, seconds)
                : String.format(Locale.ROOT, "%d:%02d", minutes, seconds);
    }

    record Display(String effectKey, String icon, String potencyKey, String duration) {
    }

    record EffectEntry(String effectId, int remainingTicks, int amplifier) {
    }
}
